<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family [
        <!ELEMENT family (properties|attributes)*>
        <!ATTLIST family
                name CDATA #REQUIRED
                parentFamily CDATA #REQUIRED
                title CDATA #REQUIRED>
        <!ELEMENT properties (property|inTitle|defaultValue|helper)*>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED>
        <!ELEMENT attributes (parentAttribute|attribute)*>
        <!ELEMENT parentAttribute (children)*>
        <!ATTLIST parentAttribute
                name CDATA #REQUIRED>
        <!ELEMENT attribute (children|properties|options)*>
        <!ATTLIST attribute
                inherited CDATA #IMPLIED
                name CDATA #REQUIRED
                type CDATA #IMPLIED>
        <!ELEMENT children (attribute|parentAttribute)*>
        <!ELEMENT inTitle (#PCDATA)>
        <!ELEMENT defaultValue (#PCDATA)>
        <!ELEMENT options (option)*>
        <!ELEMENT option (#PCDATA)>
        <!ATTLIST option
                name CDATA #REQUIRED>
        <!ELEMENT helper (file|function)*>
        <!ELEMENT file (#PCDATA)>
        <!ELEMENT function (#PCDATA)>
        ]>
<family
    name="FIRST_FAMILY" parentFamily="DEFAULT_FAMILY" title="My first family" >
    <properties>
        <property name="WID">MY_SUPER_WORKFLOW</property>
        <property name="CLASS">\MonProjet\MaClass</property>
    </properties>
    <attributes>
        <parentAttribute name="df_f_first"/>
        <attribute name="ff_f_desc" type="frame">
            <children>
                <attribute name="ff_title" type="text">
                    <properties>
                        <inTitle>true</inTitle>
                        <defaultValue><![CDATA[Du contenu    p  ]]></defaultValue>
                    </properties>
                    <options>
                        <option name="enum"><![CDATA[testounet]]></option>
                        <option name="whatisthat"><![CDATA[toutout]]></option>
                    </options>
                </attribute>
                <attribute name="ff_creator" type="account">
                    <properties>
                        <helper>
                            <file>HelperOfTheProject.php</file>
                            <function>MyHelper(CT):ff_creator</function>
                        </helper>
                        <defaultValue>::getUserId()</defaultValue>
                    </properties>
                </attribute>
                <attribute name="ff_a_redactors" type="array">
                    <children>
                        <attribute name="ff_redactor" type="account"/>
                    </children>
                </attribute>
            </children>
        </attribute>
        <parentAttribute name="df_a_files">
            <children>
                <parentAttribute name="df_file"/>
                <attribute name="ff_file_proprio" type="account"/>
                <attribute name="df_file_date" inherited="true" >
                    <properties>
                        <defaultValue>::getDate()</defaultValue>
                    </properties>
                </attribute>
            </children>
        </parentAttribute>
    </attributes>
</family>
